In [7]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyle')
np.set_printoptions(precision=2)  # reduced display precision on numpy arrays

In [8]:
x_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [13]:
print(f'X shape:{x_train.shape}, X type:{type(x_train)}')
print(x_train)
print(f'Y shape:{y_train.shape}, Y type:{type(y_train)}')

X shape:(3, 4), X type:<class 'numpy.ndarray'>
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
Y shape:(3,), Y type:<class 'numpy.ndarray'>


In [42]:
b_init = 920
w_init = np.array([4200, 12, 2, 25])
print(f'w_init shape: {w_init.shape}, b_init type: {type(b_init)}')

w_init shape: (4,), b_init type: <class 'int'>


In [43]:
def predict(x, w, b):
    p = np.dot(x, w) + b
    return p

In [44]:
x_vec = x_train[0, :]
print(f'x_vec shape: {x_vec.shape}, x_vec value: {x_vec}')

f_wb = predict(x_vec, w_init, b_init)
print(f'prediction: {f_wb}')

x_vec shape: (4,), x_vec value: [2104    5    1   45]
prediction: 8838907
